on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Direct download URL to the Discord IPA'
        required: true

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun # Node.js/npm alternative
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Bun dependencies
        run: bun install

      - name: Install Azule
        run: |
          sudo apt update
          sudo apt install libplist-utils xmlstarlet libxml2-utils -y
          git clone https://github.com/Al4ise/Azule.git ~/Azule
          cd ~/Azule
          git checkout 27c02b415cff15b1c131a0e95bcc2438023f86da # For some reason, latest version doesn't work

      - name: Download IPA
        run: wget ${{ github.event.inputs.url }} -O discord.ipa

      - name: Download Revenge
        run: |
          wget https://nightly.link/DeltAndy123/RevengeTweak/workflows/build/main/Package%20built%20by%20macos-latest.zip -O revenge.zip
          unzip revenge.zip -d revenge
          mv revenge/*.deb revenge.deb
          rm -rf revenge revenge.zip

      - name: Download Orion
        run: |
          wget https://github.com/theos/orion/releases/download/1.0.1/Orion_1.0.1.zip -O orion.zip
          unzip orion.zip -d orion
          mv orion/dev.theos.orion14*_iphoneos-arm.deb orion.deb
          rm -rf orion orion.zip

      - name: Download Sideload Fix
        run: wget https://github.com/m4fn3/DiscordSideloadFix/releases/download/v1.0.0/com.m4fn3.discord-sideload-fix_1.0.0_iphoneos-arm.deb -O sideloadfix.deb

      - name: Patch IPA icons and name
        run: bun run patch.ts

      - name: Inject Revenge and Orion
        run: ~/Azule/azule -U -i Patched.ipa -f revenge.deb orion.deb sideloadfix.deb -o . -n Revenge

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Revenge
          path: Revenge.ipa