on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Direct download URL to the Discord IPA'
        required: true

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun # Node.js/npm alternative
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Bun dependencies
        run: bun install

      - name: Install Azule
        run: |
          git clone https://github.com/Al4ise/Azule.git ~/Azule
          sudo ln -sf ~/Azule/azule /usr/local/bin/azule

      - name: Download IPA
        run: wget ${{ github.event.inputs.url }} -O discord.ipa

      - name: Download Sunset
        run: |
          wget https://nightly.link/sunset-mod/SunsetTweak/workflows/build/main/Package%20built%20by%20macos-latest.zip -O sunset.zip
          unzip sunset.zip -d sunset
          mv sunset/*.deb sunset.deb
          rm -rf sunset sunset.zip

      - name: Download Orion
        run: |
          wget https://github.com/theos/orion/releases/download/1.0.1/Orion_1.0.1.zip -O orion.zip
          unzip orion.zip -d orion
          mv orion/dev.theos.orion14*_iphoneos-arm.deb orion.deb
          rm -rf orion orion.zip

      - name: Download Sideload Fix
        run: wget https://github.com/m4fn3/DiscordSideloadFix/releases/download/v1.0.0/com.m4fn3.discord-sideload-fix_1.0.0_iphoneos-arm.deb -O sideloadfix.deb

      - name: Patch IPA icons and name
        run: bun run patch.ts

      - name: Inject Sunset and Orion
        run: ~/Azule/azule -i Patched.ipa -o Sunset.ipa -f sunset.deb orion.deb sideloadfix.deb

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sunset.ipa
          path: Sunset.ipa